### ISSUE TITLE
ReceiveOsc, SendOsc

### ISSUE THREAD

**Issue by michaelsjackson** [gbevin/ReceiveMIDI#11]
Just thought for a moment how it would be having also ReceiveOsc and SendOsc, then we could create easily cross variants like  ReceiveOsc | SendMidi, or ReceiveOsc and triggering some shell script, similarly as possible with ReceiveMidi already.  My main use case would be triggering scripts from xbox360 game controller.  Scripts which contain SendMidi   :-) , converting xbox360 to midi controllers, which can be useful if you want to trigger things independently of active windows, here midi events are very useful, they pass through any window selection or non-selection.

Thanks for sharing your great work.

**Comment by gbevin** [comment]
oscsend and oscdump already exist: https://fukuchi.org/works/oscsend/index.html.en
