### ISSUE TITLE
Triggering a script only when a specified sequence of midi notes are received? How?

### ISSUE THREAD

**Issue by michaelsjackson** [gbevin/ReceiveMIDI#14]
Thanks for sendmidi and receivemidi Geert!

I like the script triggering feature of receivemidi a lot.

```
js    code       Execute this script for each received MIDI message
jsf   path       Execute the script in this file for each message
```

How could I trigger a script when a sequence of notes is received? 

Example: If note pitches 60,61,62 in this order is received (no matter how long or short each note is, only note on sequences could be considered, ignoring note off events). The script should not trigger for 60. Also not for 61. Also not for 62. Also not for 60,61. Also not for 60,62. Also not for 61,62.  But the triple combination 60,61,62 it should trigger.

Is there any simple technique available how this could be achieved? Maybe you tried anything similar already? I know this technique from Sequetron by Phil Tipping which is its main feature. Sequetron sequencer can be controlled entirely by commands which trigger on midi note sequences.

This can be useful if the midi space should be used similarly, but this time using receivemidi, opening it for general use cases.

**Comment by gbevin** [comment]
You'd have to write this in javascript, the details of what's supported is here: https://github.com/gbevin/ReceiveMIDI/blob/master/JAVASCRIPT.md
