### ISSUE TITLE
Linux missing libraries. 

### ISSUE THREAD

**Issue by pgwalsh** [gbevin/ReceiveMIDI#15]
I have the following missing libraries on Ubuntu 20.04. 

sendmidi: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by sendmidi)
sendmidi: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by sendmidi)
sendmidi: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by sendmidi)
sendmidi: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by sendmidi)

I compiled it and works fine.

**Comment by CodexHere** [comment]
Is this project dead? There haven't been any responses, and no linux binaries for a while now.

**Comment by gbevin** [comment]
It's not feasible for me to build Linux binaries for all possible distributions and platforms. Please build it from source or ask your favorite distribution to include it as a package.
