### ISSUE TITLE
Execute Shell Script

### ISSUE THREAD

**Issue by Livefeed-nz** [gbevin/ReceiveMIDI#16]
Hi, 

Thanks for a great project.
Any chance of modifying jsf, or rather adding an option to execute a shell script/command for each message?

Thanks!

**Comment by gbevin** [comment]
You can use the Javascript interpreter to launch a shell script with `Util.command()`:
https://github.com/gbevin/ReceiveMIDI/blob/master/JAVASCRIPT.md
