### ISSUE TITLE
Commands from program file

### ISSUE THREAD

**Issue by gjs75** [gbevin/ReceiveMIDI#17]
Hi,

Thanks for this kindly tool! But how to check on different notes and execute a script. This is my command file:

`dev microKEY2`
`on C5 js "if (MIDI.isNoteOn()) Util.command('notepad.exe');"`
`on B4 js "if (MIDI.isNoteOn()) Util.command('taskkill /f /im notepad.exe');"`

But that will not work. How to combine two actions in the command file?

**Comment by gbevin** [comment]
ReceiveMIDI only runs one script upon receipt for all the MIDI messages, The `MIDI.getNoteNumber()` function in the javascript API should allow you to do conditional actions: https://github.com/gbevin/ReceiveMIDI/blob/master/JAVASCRIPT.md
