### ISSUE TITLE
Middle C displayed as C5

### ISSUE THREAD

**Issue by AndreaPro** [gbevin/ReceiveMIDI#2]
The note names in Note On and Off messages are from C0 to G10, middle C on a keyboard is usually named C3 or C4 and therefore the start note is C-2 or C-1
so it would be useful an option to choose the Middle C value between the aforementioned notes and choose one of them as default instead of displaying C5 when playing middle C.

**Comment by gbevin** [comment]
ReceiveMIDI 1.0.2 is out with a new options that allows you to set the octave for middle C.
