### ISSUE TITLE
OSC instruction blockage when data volume is large

### ISSUE THREAD

**Issue by letianletian** [gbevin/ReceiveMIDI#22]
When a large amount of data is passed in, this command will block the channel. The command line shows that it has been sent, but the OSC continues to send slowly until the blockage is resolved

**Comment by gbevin** [comment]
This is not a ReceiveMIDI issue, OSC is sent as a UDP message to the destination IP. It's very likely that your destination is getting flooded. You need to make sure that doesn't happen.
