### ISSUE TITLE
Juce Timer runs with realtime priority from jackd settings

### ISSUE THREAD

**Issue by Rippert** [gbevin/ReceiveMIDI#9]
I've been having trouble with automated scripts running jackd and receivemidi. Sometimes they end up causing RT throttling, which makes the system unresponsive. I checked with "top -H", and receivemidi was running with the -70 realtime priority I assign to jackd in it's command line. I changed the receive midi invocation to use the nice command, and that stopped receivemidi form having -70 priority, but a thread called "Juce Timer" now appears with -70 priority. 

Is there a way to get JUCE to stop trying to use my jackd priority settings?

I thought that receivemidi operated only on ALSA ports, so why is it even looking at jackd?

thanks,
-Ted

**Comment by gbevin** [comment]
Hi Ted,

This is part of the JUCE code itself, deep down in the standard JUCE Timer thread priority. Feel free to fork ReceiveMIDI and change juce_Timer.cpp to use another priority.

Take care,

Geert

**Comment by Rippert** [comment]
Thanks Geert. I actually found a blog about this that said the same thing. I tried using "ulimit -r 0" in the shell before calling receivemidi, and it worked in Arch linux, but not in Debian for some reason. So I'll look at forking your software as you suggest.
